"""empty message

Revision ID: b8b0a24fa703
Revises: 5cb59f12ef3b
Create Date: 2018-12-04 21:01:31.138959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b0a24fa703'
down_revision = '5cb59f12ef3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('skill', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'skill')
    # ### end Alembic commands ###
